services:
  mongodb:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
#   backend:
#     build: .
#     image: backend
#     container_name: backend
#     restart: always
#     ports:
#       - '3000:3000'
#     depends_on:
#       - mongodb
#     environment:
#       - MONGODB_URI=mongodb://mongodb:27017
#       - DB_NAME=dev-db

volumes:
  mongodb_data:
